server:
  port: 8889

spring:
  application.name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service/v1/product
          predicates:
            Path=/v1/product/**
          filters:
            TokenRelay=
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: my_client
            client-secret: BdmLWHaMzlikEryxsqignIZQISG3Oztv
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8889/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://localhost:8080/auth/realms/my_realm
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
